import BaseSeeder from "@ioc:Adonis/Lucid/Seeder";
import TblMarcas from "App/Infraestructura/Datos/Entidad/Marcas";

export default class extends BaseSeeder {
  public async run() {
    await TblMarcas.createMany([
      {id:1,	nombre: 'acura'},
{id:2,	nombre: 'alfa-romeo'},
{id:3,	nombre: 'aptera'},
{id:4,	nombre: 'aston-martin'},
{id:5,	nombre: 'audi'},
{id:6,	nombre: 'austin'},
{id:7,	nombre: 'bentley'},
{id:8,	nombre: 'bmw'},
{id:9,	nombre: 'bugatti'},
{id:10,	nombre: 'buick'},
{id:11,	nombre: 'cadillac'},
{id:12,	nombre: 'chevrolet'},
{id:13,	nombre: 'chrysler'},
{id:14,	nombre: 'citroen'},
{id:15,	nombre: 'corbin'},
{id:16,	nombre: 'daewoo'},
{id:17,	nombre: 'daihatsu'},
{id:18,	nombre: 'dodge'},
{id:19,	nombre: 'eagle'},
{id:20,	nombre: 'fairthorpe'},
{id:21,	nombre: 'ferrari'},
{id:22,	nombre: 'fiat'},
{id:23,	nombre: 'fillmore'},
{id:24,	nombre: 'foose'},
{id:25,	nombre: 'ford'},
{id:26,	nombre: 'geo'},
{id:27,	nombre: 'gmc'},
{id:28,	nombre: 'hillman'},
{id:29,	nombre: 'holden'},
{id:30,	nombre: 'honda'},
{id:31,	nombre: 'hummer'},
{id:32,	nombre: 'hyundai'},
{id:33,	nombre: 'infiniti'},
{id:34,	nombre: 'isuzu'},
{id:35,	nombre: 'jaguar'},
{id:36,	nombre: 'jeep'},
{id:37,	nombre: 'jensen'},
{id:38,	nombre: 'kia'},
{id:39,	nombre: 'lamborghini'},
{id:40,	nombre: 'land-rover'},
{id:41,	nombre: 'lexus'},
{id:42,	nombre: 'lincoln'},
{id:43,	nombre: 'lotus'},
{id:44,	nombre: 'maserati'},
{id:45,	nombre: 'maybach'},
{id:46,	nombre: 'mazda'},
{id:47,	nombre: 'mclaren'},
{id:48,	nombre: 'mercedes-benz'},
{id:49,	nombre: 'mercury'},
{id:50,	nombre: 'merkur'},
{id:51,	nombre: 'mg'},
{id:52,	nombre: 'mini'},
{id:53,	nombre: 'mitsubishi'},
{id:54,	nombre: 'morgan'},
{id:55,	nombre: 'nissan'},
{id:56,	nombre: 'oldsmobile'},
{id:57,	nombre: 'panoz'},
{id:58,	nombre: 'peugeot'},
{id:59,	nombre: 'plymouth'},
{id:60,	nombre: 'pontiac'},
{id:61,	nombre: 'porsche'},
{id:62,	nombre: 'ram'},
{id:63,	nombre: 'rambler'},
{id:64,	nombre: 'renault'},
{id:65,	nombre: 'rolls-royce'},
{id:66,	nombre: 'saab'},
{id:67,	nombre: 'saturn'},
{id:68,	nombre: 'scion'},
{id:69,	nombre: 'shelby'},
{id:70,	nombre: 'smart'},
{id:71,	nombre: 'spyker'},
{id:72,	nombre: 'spyker-cars'},
{id:73,	nombre: 'studebaker'},
{id:74,	nombre: 'subaru'},
{id:75,	nombre: 'suzuki'},
{id:76,	nombre: 'tesla'},
{id:77,	nombre: 'toyota'},
{id:78,	nombre: 'volkswagen'},
{id:79,	nombre: 'volvo'}
    ]);
  }
}
